version: "3.8"
services:
  #MySql Service Master
  primary:
    image: mysql:8
    container_name: mysql-primary
    restart: unless-stopped
    env_file:
      - .env.primary
    environment:
      - TZ:${TZ}
      - MYSQL_USER:${MYSQL_PASSWORD}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
      --sql_mode=NO_ENGINE_SUBSTITUTION
    cap_add:
      - all
    ports:
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
    volumes:
      - ./data:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
      - type: bind
        source: ./primary_my.cnf
        target: /etc/mysql/conf.d/my.cnf
    networks:
      - default
  secondary:
    image: mysql:8
    container_name: mysql-secondary01
    restart: unless-stopped
    env_file: .env.secondary01
    environment:
      - TZ:${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
      --sql_mode=NO_ENGINE_SUBSTITUTION
      --log-bin=mysql-bin
      --server-id=2
    cap_add:
      - all

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3307:3306"
    expose:
      # Opens port 3306 on the container
      - "3307"
    volumes:
      - ./secondary01_my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data2:/var/lib/mysql
      - ./log/mysql2:/var/log/mysql
    networks:
      - default
networks:
  default:
